[package]
name = "sagitta2-lsm-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
